paths:
  dataset_path: /home/dgist/avatar-root/dataset-generation/dataset_HSE/SMPL_augmentated_pose_variation/sample_points_camera
  checkpoint_path: ./checkpoints/

train_settings:
  batch_size: 256
  epochs: 500

  optimizer: # Adam optimizer
    lr: 1.0e-6
    betas: [0.9, 0.999]
  
  scheduler: # stepLR scheduler
    gamma: 0.1