paths:
  dataset_path: ./dataset-generation
  checkpoint_path: ./checkpoints/

train_settings:
  batch_size: 256
  epochs: 500

  optimizer: # Adam optimizer
    lr: 1.0e-6
    betas: [0.9, 0.999]
  
  scheduler: # stepLR scheduler
    gamma: 0.1

  model: RegressionPCA
  method : PCA+SMPL_VERTEX_10